// auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


//songs
export const FETCH_SONGS_START = "FETCH_SONGS_START";
export const FETCH_SONGS_SUCCESS = "FETCH_SONGS_SUCCESS";
export const FETCH_SONGS_FAIL = "FETCH_SONGS_FAIL";

export const UPDATE_SONG_START = "UPDATE_SONG_START";
export const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS";
export const UPDATE_SONG_FAIL = "UPDATE_SONG_FAIL";

export const CREATE_SONG_START = "CREATE_SONG_START";
export const CREATE_SONG_SUCCESS = "CREATE_SONG_SUCCESS";
export const CREATE_SONG_FAIL = "CREATE_SONG_FAIL";

export const DELETE_SONG_START = "DELETE_SONG_START";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";
export const DELETE_SONG_FAIL = "DELETE_SONG_FAIL";